ENG-867: Introduce build script
Percona-Lab/patchelf-packaging pull request #1
Opened 2020-05-27 09:58 UTC by Sudokamikaze

2020-05-27 10:01 UTC, Sudokamikaze commented
@EvgeniyPatlan @vorsel please review

2020-05-27 11:41 UTC, EvgeniyPatlan requested changes

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf.spec
> +%{_mandir}/man1/patchelf.1.gz
please add changelog

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf_builder.sh
> +Example $0 --builddir=/tmp/PXB --get_sources=1 --build_src_rpm=1 --build_rpm=1
PXB?

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf_builder.sh
> +            PKGLIST+=" vim-common rpmlint autoconf automake "
why do we need vim-common?

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf_builder.sh
> +        PKGLIST+=" bison make devscripts debconf debhelper automake bison autoconf automake"
don't you needed dpkg-dev to create deb package?

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf_builder.sh
> +    git clone https://github.com/Sudokamikaze/patchelf-packaging.git
why it is not included into source tarball?

2020-05-27 11:41 UTC, EvgeniyPatlan commented on patchelf_builder.sh
> +    git clone https://github.com/Sudokamikaze/patchelf-packaging.git
it should be in source tarball

2020-05-28 05:45 UTC, EvgeniyPatlan approved these changes

2020-05-28 11:21 UTC, Sudokamikaze commented
@EvgeniyPatlan @vorsel

Please, re-review, as I've added patch for https://github.com/NixOS/patchelf/issues/138
https://github.com/NixOS/patchelf/pull/127

Which affects us too

2020-06-02 06:28 UTC, EvgeniyPatlan approved these changes

2020-06-02 07:12 UTC, merged